gardenlinux/glvd

- src/glvd/cli/ingest_debsec.py
- src/glvd/data/debsec_cve.py
- src/glvd/database/__init__.py
- tests/cli/test_ingest_debsec.py
- tests/conftest.py
- tests/data/test_debsec_cve.py
We need to have all the information about CVE in Debian. This tool ingests those into a new table for later use.
> Add tool to ingest Debian Security CVE files

- src/glvd/cli/ingest_debsrc.py
- src/glvd/data/debsrc.py
- src/glvd/database/__init__.py
- tests/cli/test_ingest_debsrc.py
- tests/data/test_debsrc.py
We need to have all the information about available packages in Debian. This tool ingests the required information out of Sources files.
> Add tool to ingest Debian Sources files

- CONTRIBUTING.md
- src/glvd/database/__init__.py
- src/glvd/database/types.py
- tests/conftest.py
Turns out, Debian versions have semantic and comparing them as string does not really work. Let's use the existing `debversion` extension and type, which implements proper comparison for us.
> Use debversion extension to compare versions

- src/glvd/data/debsec_cve.py
Debian marks issues as not affected if they for example only affect Windows. Let's just ignore them completely.
> Ignore issues marked as not affected

- src/glvd/cli/combine_deb.py
- src/glvd/data/cpe.py
- tests/cli/test_combine_deb.py
- tests/data/test_cpe.py
We want to use CPE to select on granularity of source packages. So add that information as extension to standard CPE.
> Add CPE extension to store Debian information

- src/glvd/cli/ingest_debsec.py
- src/glvd/cli/ingest_debsrc.py
- tests/cli/test_ingest_debsec.py
- tests/cli/test_ingest_debsrc.py
- tests/conftest.py
In some cases, packages or CVE entries might go missing. Support deleting those entries.
> Support deletion in some ingest cases

- tests/cli/test_ingest_nvd.py
- tests/conftest.py
- tests/web/conftest.py
- tests/web/test_nvd_cve.py
SQLAlchemy supports two interfaces to work with databases, connection and session. In SQLAlchemy those where kind of combined, so a session can now also act as a connection. To make the tests easier, let's always use a session here.
> Remove support for database connection in tests

- src/glvd/web/nvd.py
We might want to have all CVE for a given source over all dists. Just allow the version to be empty supports that.
> Support search for all versions of a product

- src/glvd/database/__init__.py
- src/glvd/web/nvd.py
- tests/web/test_nvd_cve.py
PostgreSQL can actually generate JSON objects from scratch and aggregate existing JSON fields as well into lists.  While it might not be faster, it frees the currently single threaded web server.
Also we need to use JSON instead of JSONB.  The queries run about 50% faster and we don't manipulate JSON any further in the database anyway.
> Generate JSON responses inside the database

- src/glvd/data/cpe.py
- src/glvd/web/v1_cves.py
- tests/data/test_cpe.py
The web interface implementation lacked any type definitions, so all code was unchecked. Fix that and make the CPE class better usable for this case.
> Make web interface also type safe

- openapi-v1.yaml
- src/glvd/web/v1_cves.py
One of the goals of the project is to allow searching by (source) package of a finished system. This adds support for such queries.
> Allow to search by source packages

- src/glvd/cli/combine_all.py
- src/glvd/cli/combine_deb.py
- src/glvd/cli/ingest_debsec.py
- src/glvd/cli/ingest_debsrc.py
- src/glvd/cli/ingest_nvd.py
- src/glvd/web/__init__.py
SQLAlchemy can echo all queries it is executing to the log. This is just a debugging aid, so let's disable it now.
> Disable echo in SQLAlchemy

- src/glvd/cli/ingest_nvd.py
Requesting full 60 days of changes was a bit much. Let's use the last modification date and add another week. This way we should still get all changes.
> Reduce time span requested from NVD API

- src/glvd/cli/combine_deb.py
- src/glvd/data/cvss.py
- src/glvd/database/__init__.py
- src/glvd/database/types.py
- tests/cli/test_combine_deb.py
- tests/data/test_cvss.py
- tests/web/test_v1_cves.py
We want to search for CVSS severity. To do that we need to store it in an easily searchable form. At the same time we override the severity if Debian decided to call it unimportant.
> Store CVSS severity in combined deb information

- pyproject.toml
- src/glvd/cli/__init__.py
- src/glvd/cli/__main__.py
- src/glvd/cli/combine_all.py
- src/glvd/cli/combine_deb.py
- src/glvd/cli/ingest_debsec.py
- src/glvd/cli/ingest_debsrc.py
- src/glvd/cli/ingest_nvd.py
We want to make glvd easier user accessible. A command to rule them all might be a good idea.
> Provide a real script with multiple sub commands

- .github/workflows/build.yml
It turns out, `always()` also runs in case of a cancelled workflow. We don't want that, so explicitly check for success and failure.
> Only check for success and failure in actions

- .github/workflows/build.yml
The flake8 package in Debian Trixie is currently broken (see [https://bugs.debian.org/1057968](#1057968)). Temporarily ignore it's status.
> Temporarily ignore result from broken flake8

- pyproject.toml
- src/glvd/cli/client/__init__.py
- src/glvd/cli/client/__main__.py
- src/glvd/cli/client/cve.py
- tests/cli/client/test_cve.py
Add some minimal client to query single CVE.
> Add client tool to get single CVE

- src/glvd/cli/client/__init__.py
- src/glvd/cli/client/cve.py
- src/glvd/cli/data/__init__.py
- src/glvd/cli/data/combine_all.py
- src/glvd/cli/data/combine_deb.py
- src/glvd/cli/data/ingest_debsec.py
- src/glvd/cli/data/ingest_debsrc.py
- src/glvd/cli/data/ingest_nvd.py
- src/glvd/cli/registry.py
All the subcommands have a common set of arguments. Specify them only once instead of every time again.
> Factor out common arguments

- src/glvd/cli/client/cve.py
- src/glvd/cli/data/combine_all.py
- src/glvd/cli/data/combine_deb.py
- src/glvd/cli/data/ingest_debsec.py
- src/glvd/cli/data/ingest_debsrc.py
- src/glvd/cli/data/ingest_nvd.py
- src/glvd/cli/registry.py
Some of our tools might need more error handling. Provide it with the argument parser, which is also able to render error messages related to it.
> Allow manually coded error handling in CLI

- src/glvd/cli/client/__init__.py
- src/glvd/cli/data/__init__.py
- src/glvd/cli/registry.py
This PR ensures that the right program name is shown while executing glvd's CLI commands
**Which issue(s) this PR fixes**:
Fixes #55
> Fix program name for CLI commands

- README.md
- docs/01_client.md
- docs/02_server.md
- docs/03_ingestion.md
This PR contains documenation about `glvd` explaining its implementation and its functionality.
**Which issue(s) this PR fixes**:
Fixes #30
> Add some documentation about glvd to README.md

- Containerfile
cf https://metadata.ftp-master.debian.org/changelogs//main/s/sqlalchemy/sqlalchemy_2.0.30+ds1-3_changelog
> Fix image build: sqlalchemy >= 2.0 is now in unstable

- 02_ingestion-job.yaml
- deploy-k8s.sh
Run ingestion as cronjob to update the database
**Which issue(s) this PR fixes**:
Fixes https://github.com/gardenlinux/glvd/issues/102
> Run ingestion as cronjob to update the database
